development:
 adapter: posgresql
 encoding: unicode
 database: db/book-explorer-db
 pool: 5
 username: posgres
 password:

test:
  adapter: posgresql
  encoding: unicode
  database: db/book-explorer-db
  pool: 5
  username: posgres
  password:  
  timeout: 5000

production:
      adapter: postgresql
      database: my_database_production
      pool: 5
      timeout: 5000
