# Generated by Django 4.1.4 on 2023-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSVFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('book_author', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=150)),
                ('date_published', models.DateField()),
                ('book_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
