# Generated by Django 4.1.4 on 2023-02-11 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcsvfilemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadcsvfilemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
