# Generated by Django 4.0 on 2023-02-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fileManagement', '0003_csvfilemodel_csvrowsmodel_delete_uploadcsvfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfilemodel',
            name='user',
            field=models.ForeignKey(help_text='User owning this csv file', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='csvfilemodel',
            name='row_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='csvrowsmodel',
            name='file',
            field=models.ForeignKey(help_text='File owning this row content', null=True, on_delete=django.db.models.deletion.CASCADE, to='fileManagement.csvfilemodel'),
        ),
        migrations.AlterField(
            model_name='csvrowsmodel',
            name='file',
            field=models.ForeignKey(blank=True, help_text='File owning this row content', null=True, on_delete=django.db.models.deletion.CASCADE, to='fileManagement.csvfilemodel'),
        ),        
    ]
