# Generated by Django 4.1 on 2023-03-13 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileManagement', '0004_csvfilemodel_user_alter_csvfilemodel_row_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrowsmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='csvrowsmodel',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
