# Generated by Django 4.1 on 2023-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManagement', '0005_alter_csvrowsmodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfilemodel',
            name='file_aws_s3_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
