# Generated by Django 4.1 on 2023-03-20 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileManagement', '0006_csvfilemodel_file_aws_s3_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfilemodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='csvfilemodel',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
